---
title: "09.2.3.1_clusteringRobustnessByCountry"
author: "Christian Anderson"
date: "`r Sys.Date()`"
output: html_document
---

# options
```{r}
# dev.off()  # Turn off the current graphics device
# options(device = "RStudioGD")
# quartz()
options(max.print = 100)
```


# Packages
```{r, message=FALSE, warning=FALSE, results='hide', echo = TRUE}
pacman::p_load(tidyr,reshape2,purrr,tidyverse,ggplot2,gridExtra,ComplexHeatmap,viridis,zoo,mgcv,mice,ggrepel,htmltools,Metrics,psych,car,stats,lme4,lmerTest,ape,SingleCellExperiment,scater,dplyr,HDF5Array,parallel, brms,txtplot,BayesFactor,scran,bluster, TSCAN, patchwork)

rm(list = ls())
gc()
```

# functions
```{r}

# script with all functions i have made
source("/Users/canderson/Documents/LMRI/PRJ2024001/version015/analysis/00_MyFunctions.R")

```



# Load Data   
## sce
```{r}

wd_path = "~/Documents/LMRI/PRJ2024001/version015/"

how.long()
# load experiment
sce <-  loadHDF5SummarizedExperiment(paste0(wd_path, "processed_data/sce002.2.h5"))
how.long()

```

# make new directorys for plots
```{r, eval = FALSE}

a_path <- paste0(wd_path, "results/clustering//")
if(!dir.exists(a_path)) {
  dir.create(a_path, recursive = TRUE)
  
}

```

# REDO CLUSTER ORDERING AND PC1 
```{r}

# invert PC1
## rdims
pcs <- reducedDim(sce, "PCA")
pcs[,"PC1"] <- pcs[,"PC1"] * -1
reducedDim(sce, "PCA") <- pcs

## tree
pc_tree <- metadata(sce)$trajectory_data$pca_line_data
pc_tree$PC1 <- pc_tree$PC1 * -1
metadata(sce)$trajectory_data$pca_line_data <- pc_tree

# rename clusters
## order of clusteres along pseudoprog
new_cluster_names <-  data.frame(colData(sce))%>% 
  select(my_cluster, pseudoprog) %>% 
  summarize(mean_pp = mean(pseudoprog),median_pp = median(pseudoprog), .by = my_cluster) 
# my_cluster new_cluster
#          3           1
#          6           2
#          4           3
#          9           4
#          1           5
#          2           6
#         12           7
#         10           8
#          11          9
#           8         10
#           5         11
#           7         12
#          13         13
 
with(new_cluster_names,{
     plot(mean_pp,median_pp, type = "n")
     text(mean_pp,median_pp, labels = my_cluster)
     add_lines()
  })

new_cluster_names <- new_cluster_names[order(new_cluster_names$mean_pp),]
new_cluster_names$new_cluster <- seq(nrow(new_cluster_names))

## assign new cluster based on ppmean
sce$old_my_cluster <- sce$my_cluster
sce$my_cluster <- factor(new_cluster_names$new_cluster[match(as.character(sce$my_cluster), as.character(new_cluster_names$my_cluster))])

# ****** Function to replace each part of the edge ******
replace_edge_clusters <- function(edge_strs) {
  sapply(edge_strs, function(edge_str){
    parts <- strsplit(edge_str, "--")[[1]]
    new_parts <- sapply(parts, function(x) {
      new_val <- new_cluster_names$new_cluster[match(as.integer(x), new_cluster_names$my_cluster)]
      as.character(new_val)
    })
    paste(new_parts, collapse = "--")
  })
}

## replace in trees
metadata(sce)$trajectory_data$pca_line_data$old_edge<- metadata(sce)$trajectory_data$pca_line_data$edge
metadata(sce)$trajectory_data$pca_line_data$edge <- replace_edge_clusters(metadata(sce)$trajectory_data$pca_line_data$old_edge)

metadata(sce)$trajectory_data$tsne_line_data$old_edge<- metadata(sce)$trajectory_data$tsne_line_data$edge
metadata(sce)$trajectory_data$tsne_line_data$edge <- replace_edge_clusters(metadata(sce)$trajectory_data$tsne_line_data$old_edge)
```


# ______________
# look at site effect on pcs
```{r, eval =  FALSE}



plotTSNE(sce[,!is.na(sce$SITE)], color_by =I(factor(sce$SITE[!is.na(sce$SITE)])))+
  scale_color_viridis_d(option= "plasma")+
  theme(aspect.ratio = 1)


Z <- colData(sce)[, c("pc_lda_route", "SITE")] %>% 
  data.frame() %>% 
  filter(pc_lda_route!="x") %>% 
  na.omit()

nrow(Z)

Y <- (Z$pc_lda_route=="b")*1
x <- Z$SITE

X <- model.matrix(~0+factor(x))

length(Y)
nrow(X)

mod <- glm(Y~X, family = binomial) 

summary(mod) %>% 
  coef() %>% 
  as.data.frame() %>% 
  rownames_to_column("site") %>% 
  mutate(q = p.adjust(`Pr(>|z|)`)) %>% 
  ggplot(aes(Estimate, -log10(q) ))+
  # geom_point()+
  geom_label(aes(label = site))+
  geom_hline(yintercept = -log10(0.05))



Y <- as.matrix(assays(sce)$pmm_imp_of_scaled[,!is.na(sce$SITE)]) %>% 
  t()

x <- sce$SITE
X <- model.matrix(~0+factor(x))

nrow(X)
nrow(Y)

mod <- lm(Y~X)

summs <- summary(mod)

res <- sapply(summs, function(x){
  coef(x)[,1]
})
Heatmap(res)


mod <- lm(sce$pseudoprog[!is.na(sce$SITE)] ~
            model.matrix(~0+factor(sce$SITE[!is.na(sce$SITE)])))
  

res <- coef(summary(mod))
rownames(res) <- str_extract(rownames(res), "\\d+$|Intercept")

res %>% 
  as.data.frame() %>% 
  rownames_to_column("site") %>% 
  mutate(q = p.adjust(`Pr(>|t|)`)) %>% 
  ggplot(aes(Estimate, -log10(q) ))+
  # geom_point()+
  geom_label(aes(label = site))+
  geom_hline(yintercept = -log10(0.05))

  
# mod one-hot matrix of site~one-hot of cluster
Z <- cbind(site = sce$SITE, reducedDim(sce, "PCA")) %>% 
  na.omit() %>% 
  as.data.frame()

Y <- Z %>% 
  select(matches("PC")) %>% 
  as.matrix()
X <- model.matrix(~0+factor(Z$site))
 


  
mod <- lm(Y~X)
summs <-summary(mod)

res <- coef(summs[[1]])[0,]
for(i in seq(summs)){
  summ <- summs[[i]]
  coef <- as.data.frame(coef(summ))
  coef$response <- names(summs)[i] %>% 
    str_extract("PC.*$")
  coef$predictor <- rownames(coef) %>% 
    str_extract("\\d$")
  res <- rbind(res, coef)
}

res$q <- p.adjust(res$`Pr(>|t|)`, "BH")

res %>% 
  arrange(q) %>% 
  filter(q<.05) %>% 
  ggplot(aes(Estimate, -log10(q) ))+
  # geom_point()+
  geom_label(aes(label = predictor), show.legend = FALSE)+
  geom_hline(yintercept = -log10(0.05))+
  facet_wrap(~response)


reducedDim(sce, "PCA") %>% 
  as.data.frame() %>% 
  rownames_to_column("sample") %>% 
  left_join(data.frame(colData(sce)) %>% select(sample, SITE), by = "sample") %>% 
  ggplot(aes(PC4,PC6, color = factor(SITE)))+
  geom_point(show.legend = F)+
  theme_bw()+
  theme(aspect.ratio = 1)

# regress out effect of site on pcs
Z <- cbind(site = sce$SITE, reducedDim(sce, "PCA")) %>%
  na.omit() %>%
  as.data.frame()

Y <- Z %>%
  select(matches("PC")) %>%
  as.matrix()

# model pcs~ sites
mods <- apply(Y,2, function(y){
  lm(y~X)
})


summs <- sapply(mods,summary, simplify = FALSE)

res <- sapply(mods, coef) %>% 
  as.data.frame()

# residuals, error
residuals <- sapply(mods, `[[`, "residuals")


residuals %>%
as.data.frame() %>% 
  rownames_to_column("sample") %>% 
  left_join(data.frame(colData(sce)) %>% select(sample, SITE), by = "sample") %>% 
  ggplot(aes(PC4,PC6, color = factor(SITE)))+
  geom_point()


assays(sce)$pmm_imp_of_scaled %>% 
  t() %>% 
  as.data.frame() %>% 
  rownames_to_column("sample") %>% 
  left_join(data.frame(colData(sce)) %>% select(sample, SITE), by = "sample") %>% 
  group_by(SITE) %>% 
  filter(n()>30) %>% 
  summarize(across(-sample, ~mean(., na.rm = TRUE))) %>% 
  drop_na() %>% 
  column_to_rownames("SITE") %>% 
  scale() %>% 
  {(abs(.)^(2))*sign(.)} %>% 
  Heatmap()
  
```

# Site addresses
```{r}

# extract site address/country
sites <- read.csv("~/Documents/LMRI/PRJ2024001/info/site_addresses.csv")

sites <- rbind(sites, 
               tribble(
                 ~id, ~address,
                 09, 'New York, USA',
                 60, "Belfast, IR",
                 67, "LA, USA", 
                 71, "San Diego, USA",
                 72, "Basel, CH"))


sites$country <- sites$address %>% 
  str_extract(., "(?<=,\\s)\\D{1,20}$")



sites$continent <- "Europe"
sites$continent[sites$country%in%c("Australia")] <- "Australia"
sites$continent[sites$country%in%c("USA")] <- "USA"



# join to colData
sce$country <- NA
sce$country[!is.na(sce$SITE)]<- sites$country[match( sce$SITE[!is.na(sce$SITE)],sites$id)]

sce$continent <- NA
sce$continent[!is.na(sce$SITE)]<- sites$continent[match( sce$SITE[!is.na(sce$SITE)],sites$id)]

sce$continent[is.na(sce$continent)] <- "Not Classified"
  
  
table(sce$country, useNA = "always")
table(sce$continent, useNA = "always")


x <- colData(sce) %>% 
  data.frame() %>% 
  select(patID, patID_eye, month, SITE, country,continent) %>% 
  filter(continent == "Not Classified", !is.na(SITE)) %>% 
  distinct() %>% 
  pull(SITE) %>% 
  table %>% 
  as.data.frame() %>% 
  dplyr::rename_with(~c("Site", "Count"))

cat("Sites With Missing Addresses")
print(x)



```
 
## test effect of country on clustering
```{r}

# tab <- table(cluster = sce$my_cluster, country = sce$country) 
tab <- table(cluster = sce$my_cluster, continent = sce$continent) 


tab %>% 
  {print(.); .} %>% 
  chisq.test(simulate.p.value = TRUE)
# data:  .
# X-squared = 799.74, df = NA, p-value = 0.0004998

# data(raceDolls)
# ## Compute Bayes factor for independent binomial design, with
# ## columns as the fixed margin
# bf = contingencyTableBF(raceDolls, sampleType = "indepMulti", fixedMargin = "cols")
# bf
# 
# ## Posterior distribution of difference in probabilities, under alternative
# chains = posterior(bf, iterations = 10000)
# sameRaceGivenWhite = chains[,"pi[1,1]"] / chains[,"pi[*,1]"]
# sameRaceGivenBlack = chains[,"pi[1,2]"] / chains[,"pi[*,2]"]
# hist(sameRaceGivenWhite - sameRaceGivenBlack, xlab = "Probability increase",
#   main = "Increase in probability of child picking\nsame race doll (white - black)",
#   freq=FALSE, yaxt='n')
# box()


bf = contingencyTableBF(tab, posterior = FALSE, iterations = 1000, sampleType = "poisson", fixedMargin = "cols")
attributes(bf)$bayesFactor
#                        bf error               
# Non-indep. (a=1) 164.6881     0 
## ^^ observations have strong dependence

tab %>% 
  sweep(1, rowSums(.), "/") %>% 
  round(2) %>% 
  Heatmap(
    cluster_rows = FALSE,
    cluster_columns = FALSE,
    col = plasma(10)
  )

as.data.frame(tab) %>% 
  mutate(continent =  ifelse(toupper(continent)=="NONE", "Not Specified", toupper(continent))) %>% 
  mutate(total = sum(Freq), .by = cluster) %>% 
  ggplot(aes(cluster, Freq, fill = continent))+
  geom_bar(stat = "identity", position = "fill")+
  xlab("Cluster")+
  ylab("Ratio of Cluster")+
  ggtitle("Country Representation Among Clusters")+
  labs(fill = "Continent")+
  theme_classic()+
  geom_text(aes(y = 1.01, label = total), color = "grey40",size = 2)+
  theme(aspect.ratio = 1)
ggsave(sprintf("%sresults/clustering/cluster_continent_representation_prop.pdf",wd_path), height = 4, width = 5)

# plotTSNE(sce, color = "my_cluster")+
# plotTSNE(sce, color = "country")+
plotTSNE(sce, color = "continent")+
  theme(aspect.ratio = 1)+
  scale_color_discrete()
  

```


# ________
# run pipeline on different subsets by continent
## FUNCTION: ORIG clustering/trajectory pipeline; + PCA and TSNE 
```{r}

tsne_params <- metadata(sce)$params$tsne
km_nn_params <- metadata(sce)$params$km_nn


# ****** FUNCTION : cluster and trajectory analysis to give original clustering/trajectory; reduce dimensions of specified assay
og_pipeline <- function(an_sce, assay_name, 
                        reduceDims = FALSE, 
                        tsne_final_momentum = tsne_params$final_momentum, 
                        tsne_momentum = tsne_params$momentum, 
                        tsne_eta = tsne_params$eta, 
                        tsne_exageration_factor = tsne_params$exaggeration_factor, 
                        tsne_perplexity = tsne_params$perplexity, 
                        tsne_theta = NULL, 
                        tnse_seed = tsne_params$seed,
                        clust_seed = km_nn_params$seed,
                        clust_centers = km_nn_params$centers,
                        clust_k = km_nn_params$k,
                        start_node = NULL
                        ){
  require(scater)
  require(SingleCellExperiment)
  require(scran)
  
  how.long(T)
  # REDUCED DIMS ---
  if(reduceDims){
    # clear any existing reduced dimensions
    reducedDim(an_sce) <- NULL
    
    # calculate  PCs and TSNE
    an_sce <- runPCA(an_sce,exprs_values = assay_name )
    
    # dynamic argument list
    tsne_args <- list(an_sce, dimred = "PCA")
    if (!is.null(tsne_perplexity)) tsne_args$perplexity <- tsne_perplexity
    if (!is.null(tsne_theta)) tsne_args$theta <- tsne_theta
    
    # Run t-SNE with dynamically constructed arguments
    set.seed(tnse_seed)
    an_sce <- do.call(runTSNE, tsne_args)
  }
  
  # CLUSTERING ----------
  set.seed(clust_seed)
  km_nn <- clusterCells(an_sce, use.dimred="PCA",
      BLUSPARAM=TwoStepParam(
          first=KmeansParam(centers=clust_centers),
          second=NNGraphParam(k=clust_k)
      ), full = TRUE
  ) 
  
  # add clusters as labels
  colLabels(an_sce) <- km_nn$clusters
  
  # TRAJECTORY CALC ----
  # find cluster means for each var
  a_by.cluster <-  aggregateAcrossCells(an_sce , use.assay.type = assay_name, ids = an_sce$label )
  
  # PCA centroids
  a_centroids_pca <- reducedDim(a_by.cluster, "PCA")
  
  # make MST between clusters based on PCA cluster centroids
  a_mst_pca <- createClusterMST(a_centroids_pca, clusters=NULL)
  
  # edge dataframe with x,y
  a_tsne_line_data <- reportEdges(a_by.cluster, mst=a_mst_pca, clusters=NULL, use.dimred="TSNE")
  a_pca_line_data <- reportEdges(a_by.cluster, mst=a_mst_pca, clusters=NULL, use.dimred="PCA" )
  
  # map cells to nearest edge
  a_map.tscan <- mapCellsToEdges(an_sce, mst=a_mst_pca, use.dimred= "PCA")
  
  # order cells based on sequence of edges
  a_tscan.pseudo <- orderCells(a_map.tscan, a_mst_pca, start = start_node)

  # calculate pseudotime based on position in trajectory
  a_pseudoprog <- averagePseudotime(a_tscan.pseudo)
  
  # add pseudoprog to sce
  an_sce$pseudoprog <- a_pseudoprog
  
  how.long()
  
  return(list(singleCellExperiment = an_sce, trajectoryLineData = list(tsne = a_tsne_line_data, pca = a_pca_line_data)))
  
}
# test_sce_pipeline <- og_pipeline(sce)
# test_sce <- test_sce_pipeline$singleCellExperiment
# plotReducedDim(test_sce, "TSNE", color_by = "pseudoprog")

```

## make subseted sces
```{r}

sub_sces <- sapply(unique(sce$continent), function(continent){
  if(!is.na(continent)){
    sce[,sce$continent == continent & !is.na(sce$continent)]
  }else{
    sce[,is.na(sce$continent)]
  }
}, simplify = F)

names(sub_sces)[is.na(names(sub_sces) )] <- "Not Classified"

# an_sce <- sub_sces[[1]]
manipulated_objs <- mclapply(sub_sces, function(an_sce){
  og_pipeline(an_sce,assay_name = "pmm_imp_of_scaled", reduceDims = TRUE, start_node = '3')
},mc.cores = 4)

names(manipulated_objs) <- names(sub_sces)

```

## plot
```{r}

clust_traj_plots <- list()
for(i in 1:length(manipulated_objs)){

    # object list
    a_manipulated_object <- manipulated_objs[[i]]

    # grab tsne and tree data; add cluster to tsne
    # a_pca <- as.data.frame(reducedDim(a_manipulated_object$singleCellExperiment, "TSNE") )
    a_pca <- as.data.frame(reducedDim(a_manipulated_object$singleCellExperiment, "PCA") )

    # # color with manipulate data clusters
    # a_pca$og_my_cluster <- colLabels(a_manipulated_object$singleCellExperiment)

    # color with original clusters
    a_pca$og_my_cluster <- sce$my_cluster[match(rownames(a_pca), colnames(sce))]
    a_pca$og_pseudoprog <- sce$pseudoprog[match(rownames(a_pca), colnames(sce))]
    a_pca$new_pseudoprog <- a_manipulated_object$singleCellExperiment$pseudoprog

    # grab tree
    a_tree <- a_manipulated_object$trajectoryLineData$pca

    # grab centroids for labels
    cluster_labels <- a_pca %>%
      group_by(og_my_cluster) %>%
      summarize_all(median)


    # plot TSNE----
    plot <- ggplot(a_pca, aes(PC1,PC2))+
                theme_bw()+
                geom_point(show.legend =FALSE, alpha = .6, aes(color = factor(og_my_cluster)))+
                scale_color_manual(values = cluster_cols)+
                # geom_point(show.legend =FALSE, alpha = .6, aes(color =new_pseudoprog ))+
                # scale_color_viridis_c()+
                # geom_point(show.legend = FALSE, alpha = .4)+
                geom_line(data = a_tree,
                          aes(PC1, PC2, group = edge),
                          col = 'black')+
                geom_label(data = cluster_labels,
                           aes(label = og_my_cluster, x = PC1, y = PC2),
                           col = "black", alpha = .5)+
                labs(color = "og_my_cluster")+
                ggtitle(names(manipulated_objs)[i])+
                theme(aspect.ratio = 1,
                      title = element_text(face = "bold", size = 12))+
                geom_blank()

    # add plot to list
    clust_traj_plots[[i]] <- plot
}

wrap_plots(clust_traj_plots, ncol = 2)
sprintf("%sresults/clustering/09_clustering/robustness_test/%s", wd_path, "continent_clust_pcs.pdf") %>% 
  {
    ggsave(., height = 8,width = 8)
    sprintf("cp %s %s", ., sprintf("%sresults/publication_figures/%s", wd_path, basename(.))) %>% 
      system()
    }



pp_traj_plots <- list()
for(i in 1:length(manipulated_objs)){

    # object list
    a_manipulated_object <- manipulated_objs[[i]]

    # grab tsne and tree data; add cluster to tsne
    # a_pca <- as.data.frame(reducedDim(a_manipulated_object$singleCellExperiment, "TSNE") )
    a_pca <- as.data.frame(reducedDim(a_manipulated_object$singleCellExperiment, "PCA") )

    # # color with manipulate data clusters
    # a_pca$og_my_cluster <- colLabels(a_manipulated_object$singleCellExperiment)

    # color with original clusters
    a_pca$og_my_cluster <- sce$my_cluster[match(rownames(a_pca), colnames(sce))]
    a_pca$og_pseudoprog <- sce$pseudoprog[match(rownames(a_pca), colnames(sce))]
    a_pca$new_pseudoprog <- a_manipulated_object$singleCellExperiment$pseudoprog

    # grab tree
    a_tree <- a_manipulated_object$trajectoryLineData$pca

    # grab centroids for labels
    cluster_labels <- a_pca %>%
      group_by(og_my_cluster) %>%
      summarize_all(median)


    # plot TSNE----
    plot <- ggplot(a_pca, aes(PC1,PC2))+
                theme_bw()+
                # geom_point(show.legend =FALSE, alpha = .6, aes(color = factor(og_my_cluster)))+
                # scale_color_manual(values = cluster_cols)+
                geom_point(show.legend =FALSE, alpha = .6, aes(color =new_pseudoprog ))+
                scale_color_viridis_c()+
                # geom_point(show.legend = FALSE, alpha = .4)+
                geom_line(data = a_tree,
                          aes(PC1, PC2, group = edge),
                          col = 'black')+
                geom_label(data = cluster_labels,
                           aes(label = og_my_cluster, x = PC1, y = PC2),
                           col = "black", alpha = .5)+
                labs(color = "og_my_cluster")+
                ggtitle(names(manipulated_objs)[i])+
                theme(aspect.ratio = 1,
                      title = element_text(face = "bold", size = 12))+
                geom_blank()

    # add plot to list
    pp_traj_plots[[i]] <- plot
}

wrap_plots(pp_traj_plots, ncol = 2)

sprintf("%sresults/clustering/09_clustering/robustness_test/%s", wd_path, "continent_pp_pcs.pdf") %>% 
  {
    ggsave(., height = 8,width = 8); 
    sprintf("cp %s %s", ., sprintf("%sresults/publication_figures/%s", wd_path, basename(.))) %>% 
      system()
    }

```

## compare pseudotimes
```{r}

pps_names <- lapply(manipulated_objs, function(obj){
  obj$singleCellExperiment$sample
}) %>% 
  do.call(c,.) %>% 
  as.character()

pps <- lapply(manipulated_objs, function(obj){
  obj$singleCellExperiment$pseudoprog
}) %>% 
  do.call(c,.) %>% 
  as.numeric()

names(pps) <- pps_names

setdiff_intersect(list(sce$sample, names(pps)))

sce$alt_pseudoprog <- pps[match(sce$sample, names(pps))]

plot(sce$pseudoprog, sce$alt_pseudoprog, pch = 16, col = rgb(0.1,.1,.8,.05))

dat <- colData(sce) %>% 
  data.frame() %>% 
  select(patID_eye,month,continent,my_cluster,matches("alt|^pseudoprog$")) %>%
  mutate(across(matches("pseudoprog"), ~{
    sqrt(.) %>% 
      # {(.+abs(min(.)))/( max(.)-min(.))}
      scale() %>% as.numeric
  })) %>% 
  filter(n()>1, .by = patID_eye) 



dat %>% 
ggplot(aes(pseudoprog, alt_pseudoprog, group = patID_eye))+
geom_point(show.legend = FALSE,aes(color = continent,
                                   # size = ifelse(my_cluster==12, 5, 1)
                                   ),
           alpha = .3)+
# geom_line(show.legend = FALSE, alpha = .1)+
# geom_smooth(method= "gam", formula = y~s(x,k = 3),show.legend = FALSE, alpha = .1, se = FALSE, fill = 'black')+
# geom_smooth(method= "lm", show.legend = FALSE, alpha = .1, se = FALSE, color = rgb(0,0,0,.1))+
# geom_smooth(aes(group = 1),method= "gam", show.legend = FALSE, alpha = .1, se = FALSE, color = rgb(0,0,0,1))+
# geom_smooth(aes(group = 1),method= "lm", formula = y~poly(x,2), show.legend = FALSE, se = FALSE, color = rgb(0,0,0,1))+
geom_smooth(aes(group = continent, color = continent),method= "lm", formula = y~poly(x,2), show.legend = TRUE, se = TRUE)+
# geom_smooth(aes(group = continent, color = continent),method= "lm", formula = y~x, show.legend = TRUE, se = TRUE)+
theme_bw()+
ggtitle("Continental pseudoprogression versus global","values sqrted then scaled")+
theme(aspect.ratio = 1)

# RMSE of continental v global
rmse(actual = sce$pseudoprog, predicted = sce$alt_pseudoprog)

# by continent
# colData(sce)[!is.na(sce$continent) & sce$continent == "au", c("pseudoprog", "alt_pseudoprog")] %>% 
sapply(c("Australia", "Europe", "Not Classified", "USA"), function(cont){
  colData(sce)[!is.na(sce$continent) & sce$continent == cont, c("pseudoprog", "alt_pseudoprog")] %>% 
    data.frame() %>% 
    {rmse(actual = .$pseudoprog, predicted = .$alt_pseudoprog)}
})

```
