---
title: "14.2_geneticContrastModels"
author: "Christian Anderson"
date: "`r Sys.Date()`"
output: html_document
---



# Packages
```{r}

library(tidyr)
library(reshape2)
library(purrr)
library(GGally)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(gridExtra)
library(ComplexHeatmap)
library(viridis)
library(zoo)
library(plotly)
library(mgcv)
library(tools)
library(mice)
library(ggrepel)
library(htmltools)
library(Metrics)
library(psych)
library(car)
library(stats)
library(lme4)
library(lmerTest)
library(ape)
library(SingleCellExperiment)
library(scater)
library(dplyr)
library(HDF5Array)
library(parallel)
library(emmeans)
library(gplots)
library(limma)
library(optimx)

rm(list = ls())
gc()

options(max.print = 100)

```

### functions
```{r}

source("/Users/canderson/Documents/LMRI/PRJ2024001/version015/analysis/00_MyFunctions.R")

```

# Load Data
```{r}


wd_path = "~/Documents/LMRI/PRJ2024001/version015/"

a_path <- paste0(wd_path, "results/clustering/13_clustering/T2D_Modeling/")
if(!dir.exists(a_path)) {
  dir.create(a_path, recursive = TRUE)
  
}
# load experiment
sce <- HDF5Array::loadHDF5SummarizedExperiment(paste0(wd_path, "processed_data/sce007.h5"))


```
### interaction with chromosome 5

